import fs from 'fs';

function renderTemplate(template, variables = {}) {
  let out = template;
  for (const [k, v] of Object.entries(variables)) {
    out = out.replace(new RegExp(`{{${k}}}`, 'g'), String(v));
  }
  return out;
}

function extractTrendTopics(trendsText) {
  // Try to extract lines like: - Topic (0.92)
  if (!trendsText) return [];
  const lines = trendsText.split('\n');
  const topics = [];
  for (const l of lines) {
    const m = l.match(/[-*]\s*(.+?)(?:\s*\(|$)/);
    if (m) topics.push(m[1].trim());
  }
  // Fallback: if no lines matched, try comma-split
  if (topics.length === 0) {
    return trendsText.split(',').map((s) => s.trim()).filter(Boolean);
  }
  return topics;
}

export async function runPrompt(promptFile, variables = {}) {
  try {
    const promptTemplate = fs.readFileSync(promptFile, 'utf8');
    const prompt = renderTemplate(promptTemplate, variables);

    // Simple rule-based mock responses for planner/writer prompts
    if (promptFile.toLowerCase().includes('planner')) {
      // build 3 topic suggestions based on trends
      const trends = extractTrendTopics(variables.trends || prompt);
      const suggestions = [];
      for (let i = 0; i < 3; i++) {
        const topic = trends[i] || `Sample Topic ${i + 1}`;
        suggestions.push({
          title: `${topic} — What you need to know`,
          summary: `A short summary about ${topic}.`,
          topic,
        });
      }
      return JSON.stringify(suggestions, null, 2);
    }

    if (promptFile.toLowerCase().includes('writer')) {
      const topic = variables.topic || 'Unknown Topic';
      const angle = variables.angle || '';
      const title = `${topic}${angle ? ` — ${angle}` : ''}`;
      const summary = `A concise summary about ${topic}.`;
      const body = `This is a generated article about ${topic}. ${angle ? `Angle: ${angle}.` : ''}\n\nGenerated by local LLM adapter.`;
      return JSON.stringify({ title, summary, body }, null, 2);
    }

    // Default: return the filled prompt for inspection
    return prompt;
  } catch (err) {
    console.error('Local LLM Adapter Error:', err.message);
    throw { status: 500, message: 'Local LLM adapter error.' };
  }
}

export default { runPrompt };
