/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ArticleUi {
        "refresh": () => Promise<void>;
    }
}
declare global {
    interface HTMLArticleUiElement extends Components.ArticleUi, HTMLStencilElement {
    }
    var HTMLArticleUiElement: {
        prototype: HTMLArticleUiElement;
        new (): HTMLArticleUiElement;
    };
    interface HTMLElementTagNameMap {
        "article-ui": HTMLArticleUiElement;
    }
}
declare namespace LocalJSX {
    interface ArticleUi {
    }
    interface IntrinsicElements {
        "article-ui": ArticleUi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "article-ui": LocalJSX.ArticleUi & JSXBase.HTMLAttributes<HTMLArticleUiElement>;
        }
    }
}
